[package]
name = "myfetch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.8"
display-info = "0.5.1"
rand = "0.8.5"
sysinfo = "0.31.2"
systemstat = "0.2.3"
